version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: socialnetwork_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-socialnetwork}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - socialnetwork_network

  redis:
    image: redis:latest
    container_name: socialnetwork_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - socialnetwork_network

networks:
  socialnetwork_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
